const express = require("express");
const router = express.Router();
const managepackageRouter = require("./managepackage/managepackage.router");
const userInfoRouter = require("./userinfo/userinfo.router");
const mailerRouter = require("./mailer/mailer.router");
const userRouter = require("./user/user.router");
const socialuserRouter = require("./socialuser/socialuser.router");
const frontpageRouter = require("./frontpage/frontpage.router");
const offersRouter = require("./offers/offers.router");
const authenticationRouter = require("./authentication/authentication.router");
const packagebyadminRouter = require("./packagebyadmin/packagebyadmin.router");
const themeRouter = require("./clienttheme/clienttheme.router");
const supportRouter = require("./support/support.router");
const rfstationRouter = require("./rfstation/rfstation.router");
const productinfoRouter = require("./productinfo/productinfo.router");

router.use("/user", userRouter);
router.use("/socialuser", socialuserRouter);
router.use("/package", managepackageRouter);
router.use("/userinfo", userInfoRouter);
router.use("/mailer", mailerRouter);
router.use("/frontpage", frontpageRouter);
router.use("/offers", offersRouter);
router.use("/verify", authenticationRouter);
router.use("/adminpackage", packagebyadminRouter);
router.use("/theme", themeRouter);
router.use("/support", supportRouter);
router.use("/rfstation", rfstationRouter);
router.use("/productinfo", productinfoRouter);
module.exports = router;
